#define CONFIG_AVFILTER 1
#define CONFIG_AVDEVICE 1
#define CONFIG_AVUTIL 1
#define CONFIG_AVCODEC 1
#define CONFIG_AVFORMAT 1
#define CONFIG_SWRESAMPLE 1
#define CONFIG_SWSCALE 1
#define CONFIG_AVRESAMPLE 0
#define CONFIG_POSTPROC 0
#define CONFIG_MMSH_PROTOCOL 0
#define CONFIG_RTSP_DEMUXER 0
#define CONFIG_THIS_YEAR 2021
#define CC_IDENT "gcc 9.3.0"
#define FFMPEG_DATADIR "/tmp"
#define FFMPEG_CONFIGURATION "--enable-shared --enable-sdl2"
#define FFMPEG_LICENSE "LGPL version 2.1 or later"
#define HAVE_BIGENDIAN 0
#define HAVE_ALIGNED_MALLOC 0
#define HAVE_PTHREADS 1
#define HAVE_SYS_RESOURCE_H 1
#define HAVE_SDL2 1
#define HAVE_ATAN2F 1
#define HAVE_ATANF 1
#define HAVE_CBRT 1
#define HAVE_CBRTF 1
#define HAVE_COPYSIGN 1
#define HAVE_COSF 1
#define HAVE_ERF 1
#define HAVE_EXP2 1
#define HAVE_EXP2F 1
#define HAVE_EXPF 1
#define HAVE_HYPOT 1
#define HAVE_ISFINITE 1
#define HAVE_ISINF 1
#define HAVE_ISNAN 1
#define HAVE_LDEXPF 1
#define HAVE_LLRINT 1
#define HAVE_LLRINTF 1
#define HAVE_LOG10F 1
#define HAVE_LOG2 1
#define HAVE_LOG2F 1
#define HAVE_LRINT 1
#define HAVE_LRINTF 1
#define HAVE_POWF 1
#define HAVE_RINT 1
#define HAVE_ROUND 1
#define HAVE_ROUNDF 1
#define HAVE_SINF 1
#define HAVE_TRUNC 1
#define HAVE_TRUNCF 1
